services:
  - type: web
    name: strapi
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: el_diario_de_mati
    plan: free
    diskSizeGB: 1
